<? $title_tag = 'Best Dentist Turnersville | Universal Dentistry Turnersville'; ?>
<? $pageMeta = 'At Dayspring Dentistry we place the utmost importance on patient safety and quality of care.'; ?>
<? $pageKeywords ='best dentist turnersville, universal dentistry turnersville nj' ;?>

<?php include '_header.php'; ?>
<div class="mainWrap">
  <div class="bodyWrap">
    <h1>The Dayspring Experience</h1></br><p>When you first call our office, you will be greeted by our friendly, helpful office manager, Beth. She will arrange for a convenient appointment time for you, and coordinate any insurance coverage you may have. She will then send you out a new patient welcoming package with information about our office.</p></br>

    <h2>Patient Safety</h2><p>Your safety is of utmost importance to us.  All instruments, including handpieces (drills), are sterilized.  We use single-use, disposable barriers and components where we can, to protect our patients.  In addition, all of our dental systems, from our new, state of the art dental units, to our cleaning units and our Waterlase dental lasers use self-contained water supplies with distilled water.  This prevents any possibility of waterline bacterial contamination.  We also utilize an outside company to monitor the effectiveness of our sterilizer on a regular basis.</p></br>

    <h2>Philosophy</h2><p>At Dayspring Dentistry, we understand that there are about a thousand places you would rather be than at the dentist.  So, our goal is to change the things people hate the most about the dentist.
    The dreaded drill:  The Waterlase laser removes cavities with a gentle pulse of water, often without needing to be numb! The dreaded needle:  The Wand computerized anesthesia is different than any other dental anesthesia:  It's comfortable, and it doesn't look scary!  It's different than anything else out there. The dreaded wait:  We know that it's bad enough to BE at the dentist, it's worse to have to WAIT at the dentist.  We strive to stay on time, and we refuse to book 2 procedures at the same time.  So, you won't be sitting in the chair for a half hour "getting numb" while we do someone else's filling.  We won't waste your valuable time. The dreaded failure:  Everybody knows that nothing lasts forever.  Cars eventually end up in the junkyard, shoes wear out, jeans get holes in them.  Dental treatment is the same way.  Fillings, crowns, etc., all need replacement at a certain point.  But just like there is a big difference between a car that lasts 200,000 miles, and one that lasts for 50,000, there is a big difference between a crown that lasts for 3 years, and one that lasts for 10 years.  At Dayspring Dentistry, we strive for the highest quality and longevity with our treatment.  We use the highest quality materials we can find, the highest quality dental laboratories (ALL work done in the USA), and we pay attention to the closest details of your treatment.  Dentistry is a profession where the difference between success and failure is measured in microns.  Speed and high volume does not produce high quality care- meticulous attention to detail does. Request an appointment today and experience the "Difference at Dayspring".</p></br>

    <h2>Insurance</h2><p>We believe that dental insurance can be a valuable tool to help make dental care more affordable.  We participate with many insurances, including Delta, Blue Cross, Horizon, United Healthcare, and Carpenters Local.  We can help you utilize your benefits from most other insurances as well.  Unfortunately, many people do not fully understand what dental insurance really is.  It is basically a "discount coupon" towards your dental treatment.  Unlike medical insurance, which truly "insures" against problems, dental insurance gives you a percentage off your treatment, up to a very small yearly maximum.  The other problem that patients must understand is that there are 3 people involved in your treatment:  You, us, and the insurance company.  You and I care about how your treatment affects you (is it comfortable, does it solve the problem you are having, will it last a long time, etc).  The insurance company is only concerned with one thing:  how to get out of paying your claim!  We know this from years of dealing with dental insurance.  They claim to be on the patient's side, but are really only on the side of their stockholders.  We also do not participate in any HMO or DMO plans, they are set up to discourage proper oral health care.  These plans pay the dentist a couple dollars a month for you to be listed with their office.  Usually the only time they receive a payment for treatment is for larger treatment, such as root canals and crowns.  So, there is a financial incentive to the office to NOT provide routing preventive care, and to hope that you only come in for major treatment when something starts to hurt.  That is NOT how we believe dental care should be.</p>
  </div>

  <div id="sidebar"><?php include '_app.php'; ?></div>
  <div id="servCon"><?php include '_services.php'; ?></div>
</div>
<?php include '_footer.php'; ?>
